### ISSUE TITLE
Sometimes doesn't work with node version more than 12.19.x

### ISSUE THREAD

**Issue by adevnadia** [atlassian-labs/compiled#501]
It looks like that compiled _might_ have a hard dependency on node version. In my current setup, which uses next.js and atlaskit components, the build in CI (github actions if important) started failing after I added `@atlaskit/lozenge` to the mix. Babel plugin is installed.

<img width="1165" alt="failed-build" src="https://user-images.githubusercontent.com/6586830/104412151-711c7a80-55b7-11eb-858d-df889ecfc102.png">

It was mitigated by reducing node version to the version `12.16.x` from just `12.x`. Not sure how to reproduce this setup in isolation without spending days on it, hope the description and the screen will help :)

UPD:

12.15.x node version - everything is good
12.19 - fails (so starts failing somewhere in between, probably when they enabled modules support by default)
14.15.1 (latest of 14.x) - still failing
15.5.1 (latest of 14.x) - still failing

UPD:
PR with the fix: https://github.com/atlassian-labs/compiled/pull/502

**Comment by madou** [comment]
🤔 

what version of compiled in your lock file?

**Comment by adevnadia** [comment]
0.5.3

**Comment by madou** [comment]
Re: Babel plugin being installed, we have a issue to remove it https://github.com/atlassian-labs/compiled/issues/493

for lozenge, it seems CJS is then calling out to the ESM package... i wonder why?

**Comment by madou** [comment]
this issue was raised in next which was fixed with the addition of adding CJS exports https://github.com/atlassian-labs/compiled/issues/387

is anything custom in your build setup? 🤔 (or alternatively any ideas what could be happening? hehe)

**Comment by adevnadia** [comment]
Iiiinteresting 🤔 In builds there is nothing special, just `next build`, next.js is latest. And webpack config is standard next.js with `next-images` config with the addition of `babel-loader` and a few plugins (magnetic-di and emotion).

Curious why latest node solves it, maybe they made some changes there?

**Comment by adevnadia** [comment]
Okay, I slightly bullshiting here, not the latest version, it's the opposite. Managed to miss that current recommended node is already 14x. After a bit of digging and CI abusing:

* 12.15.x node version - everything is good
* 12.19 - fails (so starts failing somewhere in between)
* 14.15.1 (latest of 14.x) - still failing

**Comment by pgmanutd** [comment]
@adevnadia: I added [this comment](https://github.com/atlassian-labs/compiled/issues/387#issuecomment-744190648) for packages which are not getting transpiled by `next.js` (which are coming from `node_modules`). Can you try solution mentioned [here](https://github.com/vercel/next.js/issues/706). Looks like they are using [next-transpile-modules](https://github.com/martpie/next-transpile-modules#readme) plugin for transpiling esm packages.

**Comment by adevnadia** [comment]
@pgmanutd found a better solution here: https://github.com/atlassian-labs/compiled/pull/502

@madou if it doesn't break Atlaskit I expect a kudos from you 😝 😝 😝

**Comment by madou** [comment]
Ohh!!! Awesome, I'll take a closer look soon

Might also be good to add some more node versions into our CI run 🤔 it's
already kind of configured just need to add extra versions in

**Comment by pgmanutd** [comment]
Noice @adevnadia.
